### ISSUE TITLE
Dynamo ARN in policy.json?

### ISSUE THREAD

**Issue by tbrannam** [souvik-pl/apiLambdaDdb1#1]
The tutorial doesn't talk about how this arn should be set or updated during TF apply

https://github.com/souvik-pl/apiLambdaDdb1/blob/8be3b2f042a00fe2be67362dba433ed5c920c16f/policy.json#L14

**Comment by souvik-pl** [comment]
Hi   @tbrannam,
In the terraform code (main.tf), I have declared a DynamoDB table with the name 'myDB' (line 5). And all the ARNs for DynamoDB table are of this format - "arn:aws:dynamodb:<region>:<account ID>:table/<table name>". So, I have hard-coded that into the "policy.json" file which will authorize the Lambda function to access DynamoDB resource.

In line 21 of "main.tf" file, I have imported "policy.json" file into the terraform code, so that when we run the command "TF apply", terraform will automatically import and create the resource as declared.
